import type { Preview } from '@storybook/react-vite';
import '../src/styles/global.css';

const preview: Preview = {
  parameters: {
    options: {
      storySort: {
        method: 'alphabetical',
        locales: 'ja',
        order: [
          'Architecture',
          [
            'Handbook',
            [
              'Overview',
              'Foundation',
              [
                'Principles',
                'UI System',
                'Data and State',
                'Screen Composition',
                'Message Display',
              ],
              'Quality',
              [
                'Quality Assurance',
                'Accessibility',
                'Test Strategy',
                'Performance',
                'Animation',
                'Observability',
                'Storybook Guide',
              ],
              'Operations',
              ['Operations', 'Library Update', 'Dev Environment', 'Store Publishing'],
              'Platform',
              [
                'WebView',
                'Push Notifications',
                'Device Permissions',
                'Deep Link',
                'Offline Sync',
                'Biometric Auth',
                'File and Media',
                'I18n',
                'Feature Flags',
              ],
              'Integrations',
              ['API Communication', 'Firebase', 'AWS Mobile Services'],
            ],
          ],
          'Reference',
          [['API', ['Example OpenAPI']]],
          'App',
          [['AppErrorBoundary', 'AuthRouteGuard', 'MainAppNavigator', 'MainRouteGuard', 'RootAppShell']],
          'Feature',
          [
            ['Auth', ['LogoutButton']],
            ['Onboarding', ['PrivacyConsentScreen']],
            ['Orders', ['OrderDetailScreen', 'OrdersOverviewScreen']],
            ['Payment', ['PaymentCheckoutScreen', 'PaymentResultScreen', 'PaymentWebView']],
            ['Settings', ['AppPreferencesScreen']],
          ],
          'UI',
          [
            'Banner',
            'Button',
            'Card',
            'ConfirmDialog',
            'EmptyState',
            'ErrorState',
            'FormError',
            'FormField',
            'IconButton',
            'ImagePreview',
            'LoadingSkeleton',
            'Modal',
            'PermissionDeniedPrompt',
            'SearchBar',
            'Select',
            'Skeleton',
            'Snackbar',
            'Switch',
            'TabBar',
            'TextInput',
            'Toast',
            'WebViewContainer',
            'Layout',
            ['AuthLayout', 'MainLayout', 'Section'],
          ],
        ],
      },
    },
  },
};

export default preview;
