export const tokens = {
  colorSurfacePrimary: '#FFFFFF',
  colorSurfaceSecondary: '#F8FAFC',
  colorSurfaceElevated: '#FFFFFF',
  colorSurfaceBrand: '#175CD3',
  colorSurfaceBrandSubtle: '#E8F1FF',
  colorSurfaceDanger: '#DC2626',
  colorSurfaceDangerSubtle: '#FEF2F2',
  colorSurfaceSuccessSubtle: '#ECFDF3',
  colorSurfaceInfoSubtle: '#EFF8FF',
  colorSurfaceWarningSubtle: '#FFFAEB',
  colorSurfaceSkeleton: '#E2E8F0',
  colorSurfaceOverlay: 'rgba(15, 23, 42, 0.72)',
  colorBorderDefault: '#D0D5DD',
  colorBorderStrong: '#98A2B3',
  colorBorderDanger: '#DC2626',
  colorContentPrimary: '#101828',
  colorContentSecondary: '#475467',
  colorContentInverse: '#FFFFFF',
  colorContentDisabled: '#98A2B3',
  colorContentDanger: '#B42318',
  colorContentSuccess: '#027A48',
  colorContentInfo: '#175CD3',
  colorContentWarning: '#B54708',
  colorContentBrand: '#175CD3',
  colorFocus: '#175CD3',
  shadowCard: '0 12px 32px rgba(15, 23, 42, 0.12)',
  radiusSm: 10,
  radiusMd: 14,
  radiusLg: 20,
  space1: 4,
  space2: 8,
  space3: 12,
  space4: 16,
  space5: 20,
  space6: 24,
  controlHeightSm: 36,
  controlHeightMd: 44,
  controlHeightLg: 52,
  iconSizeSm: 16,
  iconSizeMd: 18,
  iconSizeLg: 20,
} as const;

export const typography = {
  headingMd: {
    fontSize: '20px',
    lineHeight: '28px',
    fontWeight: 600,
  },
  headingSm: {
    fontSize: '18px',
    lineHeight: '26px',
    fontWeight: 600,
  },
  bodyMd: {
    fontSize: '16px',
    lineHeight: '24px',
    fontWeight: 400,
  },
  bodySm: {
    fontSize: '14px',
    lineHeight: '20px',
    fontWeight: 400,
  },
  labelMd: {
    fontSize: '15px',
    lineHeight: '20px',
    fontWeight: 600,
  },
  labelSm: {
    fontSize: '14px',
    lineHeight: '18px',
    fontWeight: 600,
  },
} as const;

export default tokens;
